### ISSUE TITLE
npm run dev:react produce error

### ISSUE THREAD

**Issue by vziatkov** [hellosoftware-io/electron-typescript-react-mui#1]
Hi, thank you for boilerplate. 
I have noticed issue that command "dev:react" produce error
`Uncaught ReferenceError: global is not defined
    at main.js:114096
    at main.js:114565
    at main.js:114576`

**Comment by Xhale1** [comment]
I haven't been able to reproduce this issue, but I made some significant improvements to this project which should fix this issue.

Also, you should generally be using the `dev` script instead of `dev:react`.
