### ISSUE TITLE
[Resolved] Add multiple window support?

### ISSUE THREAD

**Issue by ajoslin103** [hellosoftware-io/electron-typescript-react-mui#4]
Is it possible you could add to the framework the capability to handle multiple windows with different contents?

All demos I can find only have one window type, I would like two so that my users can do two kinds of jobs.

Thanks for your work! Makes my work possible !!

**Comment by Xhale1** [comment]
Sorry for not getting to this sooner, but it looks like you figured out a solution? I'll close this but feel free to re-open this issue

**Comment by ajoslin103** [comment]
I did - and would submit a PR before too long that includes menus and windows, if you think it's good to add them

**Comment by ajoslin103** [comment]
Urgh, if anyone were to follow my approach I would have to add yet more work..  Apparently I did some things wrong...

I wonder how you would feel about merging in yet another thing :) 

https://github.com/reZach/secure-electron-template

I could collaborate on this
